language: go
go:
- 1.3
- 1.4
- 1.5
- 1.6
- 1.7
- tip

matrix:
  allow_failures:
  - go: tip

script:
- cat fixtures/infra.tf.json | go run main.go | go run main.go -reverse

before_deploy:
- shopt -s expand_aliases
- alias xcompile='go build -o json2hcl_${TRAVIS_TAG}_${GOOS}_${GOARCH} -ldflags="-X main.Version=${TRAVIS_TAG}" github.com/kvz/json2hcl'
- GOOS=linux   GOARCH=386   && xcompile
- GOOS=linux   GOARCH=amd64 && xcompile
- GOOS=linux   GOARCH=arm   && xcompile
- GOOS=darwin  GOARCH=386   && xcompile
- GOOS=darwin  GOARCH=amd64 && xcompile
- GOOS=windows GOARCH=386   && xcompile
- GOOS=windows GOARCH=amd64 && xcompile
deploy:
  provider: releases
  api_key:
    secure: "I8c5DAt7koE4L8fzQncFyGSWbHNSzj3YeWuyGGB+fLc0W1JMorMwR5b+Phph7SDc51wtEKABE+ZSEaYjp0dHLi1wVl8Z+dqmhXtwW0Oo8n7t4SgWVd6u0/nC3nUP16D1aclzYks7CzFLdaG4NCyxC3wRYkEzXrVy7d1M2mr/SoXPoLnihh3AEf51hDadP006c1lYESpNJkalM9Y+sNiGjWdSOusz+KCVZ4U0bPaTlCRMCiJQgQJYCTomEAQFLR85gooJBre/395wxgzGgxq1noPkEzy3x5EDX1VgtOfGVUJapVzO2Q5mtOhISYop1PYjN2HP8AyGC6jv3+ADVgmU4rjLdWqLxqi4wzDhDOp7rVkfY/M8Iz3YMjEM1pPkjyXgeHf38DP4oyikptW3Px57M/gwoeMnDr3FTnPNO0oVIOn91rSsfzteY1KDXdbot/GJmBWy/WRN7g4XTiFgQu9hIu5Ibe4t91qedm58Xq/PmH2kHIS1ctp7tx968kIVZlasCZAN7Ka1eQdrURKtbUiBzo9rodrQ1L33YjT4cJkAkrcphi4VHYsDQ3E6J4GjodZKW9Ps8lhYSX5Prylx1tIXYcbFmMG2lweZJy8juoaZOAEYr1WAaT+TZ5OQhsUL0rOtN13SutBHL8yi/8EjrWylL3ov5M5DooHJnUaKQsBOokU="
  file_glob: true
  file: json_2hcl_*
  skip_cleanup: true
  on:
    tags: true
    go: 1.7
    repo: kvz/json2hcl
